from unittest import TestCase


class TestSLException(TestCase):
    def test_message(self):
        self.fail()

    def test_get_message(self):
        self.fail()
